import type { BridgeName } from "./types";

export const SUPPORTED_BRIDGES_NAME_SET = new Set<BridgeName>([
	"ALEXANDER_NEVSKY",
	"ANNUNCIATION",
	"EXCHANGE",
	"BOLSHEOKHTINSKY",
	"VOLODARSKY",
	"PALACE",
	"LITEYNY",
	"TRINITY",
	"TUCHKOV",
	"SAMPSONIEVSKY",
	"GRENADERSKY",
	"KANTEMIROVSKY"
]);
