export const dict: Record<string, string> = {
	"timeline": "События",
	"lights": "Освещение",
	"sun": "Солнце",
	"moon": "Луна",
	"about": "Справка",
	"waxing": "Растущая",
	"waning": "Убывающая",
	"sunrise": "Восход Солнца",
	"sunset": "Заход Солнца",
	"no-events": "Никаких событий на сегодня",
	"error": "Произошла ошибка",
	"date-error-desc": "Выбрана неверная дата. Для решения проблемы",
	"date-error-check-url": "Проверьте адресную строку, дата должна соответствовать формату",
	"date-error-check-input": "Проверьте поле ввода даты у нижнего края экрана, выберите верное значение",
	"date-error-set-current-desc": "Либо установите текущее значение даты и времени с помощью кнопки ниже",
	"date-error-set-current": "Установить текущие время и дату",
	"lights:start": "Включение городского освещения",
	"lights:end": "Выключение городского освещения",
	"moonrise": "Восход Луны",
	"moonset": "Заход Луны",
	"dawn:astronomical": "Астрономические сумерки",
	"dawn:astronomical:info": "Ночь подходит к концу",
	"dawn:nautical": "Навигационные сумерки",
	"dawn:nautical:info": "Астрономические сумерки подходят к концу",
	"dawn:blue-hour:start": "Утренний синий час",
	"dawn:civil": "Гражданские сумерки",
	"dawn:civil:info": "Навигационные сумерки подходят к концу",
	"dawn:blue-hour:end": "Утренний синий час подходит к концу",
	"dawn:golden-hour:start": "Утренний золотой час",
	"dawn:golden-hour:start:info": "Гражданские сумерки подходят к концу",
	"sunrise:start": "Рассвет Солнца",
	"sunrise:start:info": "Солнечный диск появляется у горизонта",
	"sunrise:end": "Рассвет подходит к концу",
	"sunrise:end:info": "Солнечный диск вышел за горизонт",
	"dawn:golden-hour:end": "Утренний золотой час подходит к концу",
	"dawn:golden-hour:end:info": "Начало солнечного дня",
	"solar-noon": "Солнце в зените",
	"dusk:golden-hour:start": "Вечерний золотой час",
	"dusk:golden-hour:start:info": "Солнечный день подходит к концу",
	"sunset:start": "Закат Солнца",
	"sunset:start:info": "Солнечный диск касается горизонта",
	"sunset:end": "Закат Солнца подходит к концу",
	"sunset:end:info": "Солнечный диск ушёл за горизонт",
	"dusk:golden-hour:end": "Гражданские сумерки",
	"dusk:blue-hour:start": "Вечерний синий час",
	"dusk:blue-hour:start:info": "Золотой час подходит к концу",
	"dusk:civil": "Навигационные сумерки",
	"dusk:civil:info": "Гражданские сумерки подходят к концу",
	"dusk:blue-hour:end": "Вечерний синий час подходит к концу",
	"dusk:nautical": "Астрономические сумерки",
	"dusk:nautical:info": "Навигационные сумерки подходят к концу",
	"dusk:astronomical": "Начало ночи",
	"dusk:astronomical:info": "Астрономические сумерки подходят к концу",
	"nadir": "Солнце в надире",
	"nadir:info": "Темнейший момент ночи",
	"saint-petersburg": "г. Санкт-Петербург",
	"next-day": "Следующий день",
	"prev-day": "Предыдущий день",
	"date-and-time": "Дата и время",
	"header-lights-by-date": "Данные об освещении по датам",
	"header-lights-timer": "Отсчёт переключения подсветки",
	"header-moon-moontimes": "Времена восхода и захода Луны",
	"header-moon-phase-calendar": "Календарь Лунных фаз",
	"header-sun-moontimes": "Времена восхода и захода Солнца"
};
