export const dict: Record<string, string> = {
	"timeline": "События",
	"lights": "Освещение",
	"sun": "Солнце",
	"moon": "Луна",
	"about": "Справка",
	"lights:start": "Включение городского освещения",
	"lights:end": "Выключение городского освещения",
	"sunrise": "Восход Солнца",
	"sunset": "Заход Солнца",
	"moonrise": "Восход Луны",
	"moonset": "Заход Луны",
	"dawn:astronomical": "Рассвет астрономический",
	"dawn:nautical": "Рассвет навигационный",
	"dawn:blue-hour:start": "Рассветный синий час, начало",
	"dawn:civil": "Рассвет гражданский",
	"dawn:blue-hour:end": "Рассветный синий час, конец",
	"dawn:golden-hour:start": "Рассветный золотой час, начало",
	"sunrise:start": "Начало рассвета",
	"sunrise:end": "Конец рассвета",
	"dawn:golden-hour:end": "Рассветный золотой час, конец",
	"solar-noon": "Солнечный полдень",
	"dusk:golden-hour:start": "Сумеречный золотой час, начало",
	"sunset:start": "Начало заката",
	"sunset:end": "Конец заката",
	"dusk:golden-hour:end": "Сумеречный золотой час, конец",
	"dusk:blue-hour:start": "Сумеречный синий час, начало",
	"dusk:civil": "Сумерки гражданские",
	"dusk:blue-hour:end": "Сумеречный синий час, конец",
	"dusk:nautical": "Сумерки навигационные",
	"dusk:astronomical": "Сумерки астрономические",
	"nadir": "Темнейшая ночь"
};
