export const dict = {
	"timeline": "События",
	"lights": "Освещение",
	"sun": "Солнце",
	"moon": "Луна",
	"about": "Справка",
	"settings": "Настройки",
	"preferences": "Предпочтения",
	"starting-page": "Стартовая страница",
	"latitude": "Широта",
	"longitude": "Долгота",
	"geoposition": "Геолокация",
	"get-geo-device": "Запросить данные с устройства",
	"get-geo-device-success": "Данные обновлены",
	"get-geo-device-danger": "Не удалось получить данные",
	"save": "Сохранить",
	"reset": "Сбросить",
	"waxing": "Растущая",
	"waning": "Убывающая",
	"sunrise": "Восход Солнца",
	"sunset": "Заход Солнца",
	"warning": "Предупреждение",
	"no-events": "Никаких событий на сегодня",
	"duration-lights": "Длительность освещения",
	"duration-daylight": "Длительность солнечного дня",
	"something-wrong": "Что-то пошло не так...",
	"error": "Произошла ошибка",
	"date-error-desc": "Выбрана неверная дата. Для решения проблемы",
	"date-error-check-url": "Проверьте адресную строку, дата должна соответствовать формату",
	"date-error-check-input": "Проверьте поле ввода даты у нижнего края экрана, выберите верное значение",
	"date-error-set-current-desc": "Либо установите текущее значение даты и времени с помощью кнопки ниже",
	"date-error-set-current": "Установить текущие время и дату",
	"lights:start": "Включение городского освещения",
	"lights:end": "Выключение городского освещения",
	"moonrise": "Восход Луны",
	"moonset": "Заход Луны",
	"astronomical:dawn": "Астрономические сумерки",
	"astronomical:dawn:info": "Ночь подходит к концу",
	"nautical:dawn": "Навигационные сумерки",
	"nautical:dawn:info": "Астрономические сумерки подходят к концу",
	"blue-hour:dawn:start": "Утренний синий час",
	"civil:dawn": "Гражданские сумерки",
	"civil:dawn:info": "Навигационные сумерки подходят к концу",
	"blue-hour:dawn:end": "Утренний синий час подходит к концу",
	"golden-hour:dawn:start": "Утренний золотой час",
	"golden-hour:dawn:start:info": "Гражданские сумерки подходят к концу",
	"sunrise:start": "Рассвет Солнца",
	"sunrise:start:info": "Солнечный диск появляется у горизонта",
	"sunrise:end": "Рассвет подходит к концу",
	"sunrise:end:info": "Солнечный диск вышел за горизонт",
	"golden-hour:dawn:end": "Утренний золотой час подходит к концу",
	"golden-hour:dawn:end:info": "Начало солнечного дня",
	"solar-noon": "Солнце в зените",
	"golden-hour:dusk:start": "Вечерний золотой час",
	"golden-hour:dusk:start:info": "Солнечный день подходит к концу",
	"sunset:start": "Закат Солнца",
	"sunset:start:info": "Солнечный диск касается горизонта",
	"sunset:end": "Закат Солнца подходит к концу",
	"sunset:end:info": "Солнечный диск ушёл за горизонт",
	"golden-hour:dusk:end": "Гражданские сумерки",
	"blue-hour:dusk:start": "Вечерний синий час",
	"blue-hour:dusk:start:info": "Золотой час подходит к концу",
	"blue-hour:dusk:end": "",
	"civil:dusk": "Навигационные сумерки",
	"civil:dusk:info": "Гражданские сумерки подходят к концу",
	"dusk:blue-hour:end": "Вечерний синий час подходит к концу",
	"nautical:dusk": "Астрономические сумерки",
	"nautical:dusk:info": "Навигационные сумерки подходят к концу",
	"astronomical:dusk": "Начало ночи",
	"astronomical:dusk:info": "Астрономические сумерки подходят к концу",
	"nadir": "Солнце в надире",
	"nadir:info": "Темнейший момент ночи",
	"saint-petersburg": "г. Санкт-Петербург",
	"moscow": "г. Москва",
	"next-day": "Следующий день",
	"prev-day": "Предыдущий день",
	"date-and-time": "Дата и время",
	"header-lights-by-date": "Данные об освещении по датам",
	"header-lights-timer": "Отсчёт переключения подсветки",
	"header-moon-moontimes": "Времена восхода и захода Луны",
	"header-moon-phase-calendar": "Календарь Лунных фаз",
	"header-sun-moontimes": "Времена восхода и захода Солнца",
	"update": "Обновление",
	"update-message": "Обновление готово к установке. Для установки, пожалуйста, перезагрузите приложение или страницу.",
	"reload": "Перезапустить",
	"new-moon": "Новолуние",
	"waxing-crescent": "Растущий месяц",
	"first-quarter": "Первая четверть",
	"waxing-gibbous": "Растущая Луна",
	"full-moon": "Полнолуние",
	"waning-gibbous": "Убывающая Луна",
	"third-quarter": "Третья четверть",
	"waning-crescent": "Убывающий месяц",
	"bridge": "мост",
	"bridges": "Разводные мосты",
	"alexander-nevsky": "Александра Невского",
	"exchange": "Биржевой",
	"annunciation": "Благовещенский",
	"bolsheokhtinsky": "Большеохтинский",
	"volodarsky": "Володарский",
	"palace": "Дворцовый",
	"liteyny": "Литейный",
	"trinity": "Троицкий",
	"tuchkov": "Тучков",
	"sampsonievsky": "Сампсониевский",
	"grenadersky": "Гренадёрский",
	"kantemirovsky": "Кантемировский",
	"bridge-opened": "Разведён",
	"bridge-closed": "Сведён",
	"bridge-exception": "Разводка этого моста производится по предварительной заявке за 2 суток.",
	"bridge-schedule-spb": "Расписание разведения мостов г. Санкт-Петербург",
	"navigation-opened": "Навигация открыта",
	"navigation-closed": "Навигация закрыта",
	"till-navigation": "До начала навигации",
	"closest-event": "Ближайшее событие",
	"off": "Отключить"
};

export const template = {
	"lights-event": (state: boolean) => `Городское освещение будет <strong>${state ? "выключено" : "включено"}</strong> через`,
	"hours-and-minutes": (arg: [ hours: number, minutes: number ]) => {
		const map = {
			"zero": [ "часов", "минут" ],
			"one": [ "час", "минута" ],
			"two": [ "часа", "минуты" ],
			"few": [ "часа", "минуты" ],
			"other": [ "часов", "минут" ],
			"many": [ "часов", "минут" ]
		};

		const rules = new Intl.PluralRules("ru-RU");

		return `${arg[0]} ${map[rules.select(arg[0])][0]} ${arg[1]} ${map[rules.select(arg[1])][1]}`;
	},
	"bridge-next-event": (state: boolean) => {
		return `Мост будет ${state ? "сведён" : "разведён"} через`;
	},
	"days": (days: number) => {
		const plurals = {
			"zero": "дней",
			"one": "день",
			"two": "дня",
			"few": "дня",
			"other": "дни",
			"many": "дней"
		};

		return plurals[new Intl.PluralRules("ru-RU").select(days)];
	}
};
